name = "ISMRMRD"
uuid = "9b134852-0d9b-49f5-83c7-edc5c45cd76e"
version = "0.1.0"
authors = ["oscar <oscarvanderheide@gmail.com>"]

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"

[compat]
HDF5 = "0.16, 0.17"
LightXML = "0.9"
julia = "1.9"
